import json
import pandas as pd
from tkinter import filedialog as fd
import pyautogui as pa
import pyperclip as pc
import time
from tkinter import *

print("파일 불러오기")
sh_name = input('시트 이름: ')
try:
    df = pd.read_excel("test.xlsx", sheet_name=sh_name)
    print(df)
except:
    print("시트 이름이 잘못되었습니다.")
    exit()

while(True):
    num = input('기관 수: ')
    sum = input("시작 행: ")
    
    print("빵 등록")
    
    row_num = int(sum)
    data_fr = df.iloc[row_num]
    print("기관 명:"+ str(data_fr.iloc[0]))
    print(row_num)
    
    pa.hotkey('alt', 'tab')
    time.sleep(0.5)
    for i in range(int(num)):
        print(i)
        data = df.iloc[row_num+i]
        # print(data)
        print("기관명: "+str(data.iloc[1]))
        print("만약 20000원 이면 케이크로 등록")
        if data.iloc[3] == 20000:
            print("케이크 등록")
            pa.click(x=454, y=199)
            time.sleep(0.5)
            pa.click(x=1434, y=284)
            time.sleep(0.5)
            pa.click(x=709, y=357)
            time.sleep(0.5)
            pa.click(x=1168, y=362)
            pc.copy(str(data.iloc[1]))
            pa.hotkey('ctrl', 'v')
            time.sleep(0.5)
            pa.press('f2')
            time.sleep(0.5)
            pa.click(x=953, y=467, clicks=2, button='left')
            time.sleep(0.2)
            pa.click(x=1872, y=431)
            time.sleep(0.5)
            pa.click(x=955, y=455)
            time.sleep(0.5)
            pc.copy('기타케익')
            pa.hotkey('ctrl', 'v')
            time.sleep(0.5)
            pa.click(x=1101, y=453)
            time.sleep(0.5)
            pa.press('f2')
            time.sleep(0.5)
            pa.click(x=1069, y=526, clicks=2, button='left')
            time.sleep(0.2)
            pa.click(x=950, y=767)
            time.sleep(0.2)
            pa.click(x=736, y=504)
            pc.copy(str(data.iloc[2]))
            time.sleep(0.2)
            pa.hotkey('ctrl', 'v')
            pa.press('tab')
            pc.copy(str(int(data.iloc[2])))
            pa.hotkey('ctrl', 'v')
            pa.press('tab')
            pa.press('tab') 
            pa.press('tab')
            pa.press('tab')
            pc.copy(str(data.iloc[4]))
            pa.hotkey('ctrl', 'v')
            time.sleep(0.2)
            pa.click(x=1867, y=281)
            pa.press('enter')
            time.sleep(0.2)
            pa.press('enter')
            time.sleep(0.2)
            pa.press('enter')
            time.sleep(0.2)
        else:
            print("빵 등록")
            pa.click(x=454, y=199)
            time.sleep(0.5)
            pa.click(x=1434, y=284)
            time.sleep(0.5)
            pa.click(x=709, y=357)
            time.sleep(0.5)
            pa.click(x=1168, y=362)
            pc.copy(str(data.iloc[1]))
            pa.hotkey('ctrl', 'v')
            time.sleep(0.5)
            pa.press('f2')
            time.sleep(0.5)
            pa.click(x=953, y=467, clicks=2, button='left')
            time.sleep(0.2)
            pa.click(x=1872, y=431)
            time.sleep(0.5)
            pa.click(x=955, y=455)
            time.sleep(0.5)
            pc.copy('기타빵')
            pa.hotkey('ctrl', 'v')
            time.sleep(0.5)
            pa.click(x=1101, y=453)
            time.sleep(0.5)
            pa.press('f2')
            time.sleep(0.5)
            pa.click(x=1069, y=526, clicks=2, button='left')
            time.sleep(0.2)
            pa.click(x=950, y=767)
            time.sleep(0.2)
            pa.click(x=736, y=504)
            pc.copy(str(data.iloc[2]))
            time.sleep(0.2)
            pa.hotkey('ctrl', 'v')
            time.sleep(0.2)
            pa.press('tab')
            time.sleep(0.2)
            pc.copy(str(int(int(data.iloc[2])/5)))
            pa.hotkey('ctrl', 'v')
            print(int(int(data.iloc[2])/5))
            pa.press('tab')
            pa.press('tab')
            pa.press('tab')
            pa.press('tab')
            pc.copy(str(data.iloc[4]))
            pa.hotkey('ctrl', 'v')
            time.sleep(0.2)
            pa.click(x=1867, y=281)
            pa.press('enter')
            time.sleep(0.2)
            pa.press('enter')
            time.sleep(0.2)
            pa.press('enter')
            time.sleep(0.2)

    pa.hotkey('alt', 'tab')
    print("빵 제공")
    
    end = input("종료하시겠습니까? (y/n)")
    if end == 'y':
        break
    else:
        print(df)
        continue